version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./data:/opt/keycloak/data
    ports:
      - "8080:8080"

